name: tests

on:
  workflow_run:
    workflows: ["contracts"]
    types: [completed]

jobs:
  hardhat-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.10.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - name: Configure pnpm
        run: pnpm config set node-linker hoisted

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run Hardhat tests
        run: pnpm test
